name: Auto-Merge on Collaborator Commit

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge if collaborator commits
      id: auto_merge
      run: |
        # Check if the commit was made by a collaborator
        PR_NUM=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq -r '.[] | select(.head.ref == env.GITHUB_REF) | .number')
        COLLABORATOR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUM" | jq -r '.user.login')

        if [[ "$COLLABORATOR" == "${{ github.actor }}" ]]; then
          echo "The commit was made by a collaborator: $COLLABORATOR. Merging PR #$PR_NUM..."
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUM/merge"
          echo ::set-output name=pr_number::$PR_NUM
          echo ::set-output name=collaborator::$COLLABORATOR
        else
          echo "The commit was not made by a collaborator. No action required."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Status Check
      if: always()
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: "success",
            target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${{ github.run_id }}`,
            description: "Merge PR #" + "${{ steps.auto_merge.outputs.pr_number }}" + " by " + "${{ steps.auto_merge.outputs.collaborator }}",
            context: "Merge Status Check"
          })
