name: Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Deploy Streamlit app
      run: streamlit run app.py  # Replace 'app.py' with the name of your Streamlit app script
