name: Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Streamlit App Locally
      run: streamlit run app.py &
  
    - name: Wait for Streamlit App
      run: |
        sleep 10  # Wait for 10 seconds for the Streamlit app to start
      continue-on-error: true  # Continue even if sleep fails

    - name: Display Local URL
      run: |
        echo "Your Streamlit app is running locally at http://localhost:8501"  # Adjust the URL as needed
